name: Deployment

on:
  push:
    branches:
      - development
  pull_request:
    types: [closed]
    branches:
      - development
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build JavaScript/CSS for Staging Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: "8.1"
          extensions: csv, mbstring, bcmath

      - name: Composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: YARN Build
        run: |
          yarn install
          yarn prod

      - name: Put built assets in Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: public
          retention-days: 1

  deploy-staging:
    name: Deploy Project to Staging Server
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/development'
    steps:
      - uses: actions/checkout@v3
      - name: Fetch built assets from Artifacts
        uses: actions/download-artifact@v3
        with:
          name: assets
          path: public

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: "8.1"
          extensions: csv, mbstring, bcmath

      - name: Composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Setup SSH for deployer staging
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS_STAGING }}
          if_key_exists: replace

      - name: Deploy to Staging
        env:
          DOT_ENV: ${{ secrets.DOT_ENV_STAGING }}
        run: php vendor/bin/dep deploy staging --branch="main" -vv

  deploy-production:
    name: Deploy Project to Production Server
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Fetch built assets from Artifacts
        uses: actions/download-artifact@v3
        with:
          name: assets
          path: public
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: "8.1"
          extensions: csv, mbstring, bcmath
      - name: Composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Setup SSH for deployer
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: replace
      - name: Setup Deployer
        uses: atymic/deployer-php-action@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Deploy to Production
        env:
          DOT_ENV: ${{ secrets.DOT_ENV_PRODUCTION }}
        run: php vendor/bin/dep deploy productin --branch="main" -vv
