<?php

return [
    'maxDocumentSizeUpload' => '10mb',
    'maxImageSizeUpload' => '10mb',
    'child_protection_indices_category' => [
        'Indeks Perlindungan Anak',
        'Indeks Pemenuhan Hak Anak',
        'Indeks Perlindungan Khusus Anak',
    ],
    'location' => [
        'Kota Yogyakarta',
        'Kabupaten Bantul',
        'Kabupaten Gunungkidul',
        'Kabupaten Sleman',
        'Kabupaten Kulon Progo',
        'Daerah Istimewa Yogyakarta',
    ],
    'rule_type' => [
        'Peraturan Daerah',
        'Peraturan Gubernur',
        'Peraturan Bupati / Walikota',
        'Keputusan Gubernur',
        'Keputusan Bupati / Walikota',
        'Dokumen Lainnya',
    ],
    'recapitulation_category' => [
        'Regulasi KLA',
        'Perlindungan Anak',
        'RAD KLA',
        'Profil Anak',
        'Gugus Tugas',
    ],

    'birth_certificate_category' => [
        'Jumlah Anak',
        'Persentase Jumlah Anak',
        'Kepemilikan Akta Kelahiran',
        'Persentase Kepemilikan Akta Kelahiran',
    ],

    'child_identity_card_category' => [
        'Jumlah Anak',
        'Persentase Jumlah Anak',
        'Kepemilikan KIA',
        'Persentase Kepemilikan KIA',
    ],

    'perkawinan_anak_category' => [
        'Dispensasi Perkawinan ',
        'Anak Menikah di Bawah Umur',
        'Kasus Perkawinan Anak',
    ],

    'family_consultancy' => [
        'category' => [
            'Puspaga',
            'LK3',
            'PPKS',
            'Bina Keluarga Remaja',
            'Bina Keluarga Balita',
            'Pusat Informasi dan Konseling Remaja',
            'Lain-lain',
        ],
        'recapitulation_category' => [
            'Lembaga Konsultasi',
            'Klien',
        ],
    ],

    'bprs' => [
        'category' => [
            'Ruang Pimpinan',
            'Ruang Kerja Staf',
            'Ruang Rapat',
            'Ruang Tamu',
            'Ruang Dokumentasi',
            'Ruang Data dan Informasi',
            'Ruang Pelayanan Teknis',
            'Peralatan Lembaga rehabilitasi sosial',
            'Alat transportasi',
            'Sandang dan pangan bagi anak',
            'Lainnya',
        ],
    ],

    'lpka' => [
        'category' => [
            'Ruang Pimpinan',
            'Ruang Kerja Staf',
            'Ruang Rapat',
            'Ruang Tamu',
            'Ruang Dokumentasi',
            'Ruang Data dan Informasi',
            'Ruang Pelayanan Teknis',
            'Peralatan Lembaga rehabilitasi sosial',
            'Alat transportasi',
            'Sandang dan pangan bagi anak',
            'Lainnya',
        ],
        'jenis_ruangan' => [
            'Ruang Kunjungan Keluarga Anak',
            'Ruang Pendidikan Formal',
            'Ruang Pendidikan Non Formal',
            'Ruang Layanan Kesehatan',
            'Ruang Pembinaan Mental, Spritual dan Sosial',
            'Tempat Olahraga',
            'Tempat/Ruang Serbaguna',
            'Kotak Pengaduan Anak',
            'lainnya',
        ],
        'daftar_sop' => [
            'Ruang Kunjungan Keluarga Anak',
            'Ruang Pendidikan Formal',
            'Ruang Pendidikan Non Formal',
            'Ruang Layanan Kesehatan',
            'Ruang Pembinaan Mental, Spritual dan Sosial',
            'Tempat Olahraga',
            'Tempat/Ruang Serbaguna',
            'Kotak Pengaduan Anak',
            'lainnya',
        ],
        'sarana_prasarana' => [
            'Papan petunjuk',
            'Titik Kumpul',
            'APAR',
            'Lainnya',
        ]
    ],

    'pengadilan' => [
        'daftar_sop' => [
            'Ruang tunggu ramah anak',
            'Ruang Sidang Ramah Anak',
            'Ruang Teleconference',
            'Ruang Mediasi',
            'Ruang Tunggu PK BAPAS, Peksos, dan Penasehat Hukum'
        ],
        'sarana_prasarana' => [
            'Ruang tunggu ramah anak',
            'Ruang Sidang Ramah Anak',
            'Ruang Teleconference',
            'Ruang Mediasi',
            'Ruang Tunggu PK BAPAS, Peksos, dan Penasehat Hukum',
        ]
    ],
    'kelurahan' => [
        'category' => [
            'Kalurahan / Kelurahan',
            'Kapanewon / Kemantren',
            'Gugus Tugas',
            'Profil Anak',
            'Forum Anak',
            'Ruang Bermain Ramah Anak',
            'Pusat Informasi Sahabat Anak',
            'Pusat Kreatifitas Anak',
            'Satgas PPA',
            'Pusat Kreatifitas Anak',
            'PATBM',
            'PIKR',
            'Kawasan Tanpa Rokok',
        ],
        'kalurahan_kelurahan' => [
            'Girikerto',
            'Bangunkerto',
            'Wedomartani',
            'Pandowoharjo',
            'Jatimulyo',
            'Bejiharjo',
            'Putat',
            'Pagerharjo',
            'Sabdodadi',
            'Margodadi',
            'Merdikorejo',
            'Widodomartani',
            'sumberagung',
        ],
        'kabupaten' => [
            'Bantul',
            'Gunungkidul',
            'Kulonprogo',
            'Sleman',
            'Yogyakarta',
        ],
        'profil_anak' => [
            'Ada',
            'Belum Ada',
        ],
        'forum_anak' => [
            'Ada',
            'Belum Ada',
        ],
        'ruang_bermain' => [
            'Ada',
            'Belum Ada',
        ],
        'profil_anak' => [
            'Ada',
            'Belum Ada',
        ],
        'pusat_informasi' => [
            'Perpustakaan',
            'Taman Bacaan Masyarakat',
        ],

        'pusat_kreatifitas' => [
            'Seni',
            'Olahraga',
            'Kriya',
        ],
        'satgas_ppa' => [
            'Ada',
            'Belum Ada',
        ],
        'patbm' => [
            'Ada',
            'Belum Ada',
        ],
        'pikr' => [
            'Ada',
            'Belum Ada',
        ],
        'kawasan_tanpa_rokok' => [
            'Ada',
            'Belum Ada',
        ],
    ],
    'kapanewon' => [
        'category' => [
            'Kapanewon / Kemantren',
            'Gugus Tugas',
            'Profil Anak',
            'Forum Anak',
            'Ruang Bermain Ramah Anak',
            'Pusat Informasi Sahabat Anak',
            'Pusat Kreatifitas Anak',
            'Satgas PPA',
            'Pusat Kreatifitas Anak',
            'PATBM',
            'PIKR',
            'Kawasan Tanpa Rokok',
        ],
        'kapanewon_kemantren' => [
            'Kecamatan Mergangsan',
            'Kecamatan Karangmojo',
            'Kecamatan Purwosari',
            'Kecamatan Nglipar',
            'Pakem',
            'widodomartani',
            'Kapanewonan pundong',
        ],
        'kabupaten' => [
            'Bantul',
            'Gunungkidul',
            'Kulonprogo',
            'Sleman',
            'Yogyakarta',
        ],
        'profil_anak' => [
            'Ada',
            'Belum Ada',
        ],
        'forum_anak' => [
            'Ada',
            'Belum Ada',
        ],
        'ruang_bermain' => [
            'Ada',
            'Belum Ada',
        ],
        'profil_anak' => [
            'Ada',
            'Belum Ada',
        ],
        'pusat_informasi' => [
            'Perpustakaan',
            'Taman Bacaan Masyarakat',
        ],

        'pusat_kreatifitas' => [
            'Seni',
            'Olahraga',
            'Kriya',
        ],
        'satgas_ppa' => [
            'Ada',
            'Belum Ada',
        ],
        'patbm' => [
            'Ada',
            'Belum Ada',
        ],
        'pikr' => [
            'Ada',
            'Belum Ada',
        ],
        'kawasan_tanpa_rokok' => [
            'Ada',
            'Belum Ada',
        ],
    ],
    'patbm' => [
        'category' => [
            'Kelurahan Trihanggo',
            'Kelurahan Mororejo',
            'Kelurahan Kemadang',
            'Kelurahan Ngalang',
            'Kelurahan Karangrejek',
            'Kelurahan Dengok',
            'Kelurahan Banaran',
            'Pathuk',
            'Kelurahan Gilangharjo',
            'Kelurahan Kembang',
            'Kelurahan Tegalpanggung',
            'Kelurahan Bausasran',
            'Kelurahan Pringgokusuman',
            'Kelurahan Sosromenduran',
            'Kelurahan Baciro',
            'Kelurahan Demangan',
            'Kelurahan Kotabaru',
            'Kelurahan Klitren',
            'Kelurahan Terban',
            'Kelurahan Prawirodirjan',
            'Kelurahan Ngupasan',
            'Kelurahan Bumijo',
            'Kelurahan Cokrodiningratan',
            'Kelurahan Prenggan',
            'Kelurahan Purbayan',
            'Kelurahan Kadipaten',
            'Kelurahan Patehan',
            'Kelurahan Panembahan',
            'Kelurahan Mantrijeron',
            'Kelurahan Wirogunan',
            'Kelurahan Brontokusuman',
            'Kelurahan Ngampilan',
            'Kelurahan Notoprajan',
            'Kelurahan Gunungketur',
            'Kelurahan Purwokinanti',
            'Kelurahan Tegalrejo',
            'Kelurahan Bener',
            'Kelurahan Semaki',
            'Kelurahan Warungboto',
            'Kelurahan Pandeyan',
            'Kelurahan Sorosutan',
            'Kelurahan Giwangan',
            'Kelurahan Tahunan',
            'Kelurahan Wirobrajan',
            'Kelurahan Patangpuluhan',
            'Kelurahan Pakuncen',
            'Wukirsari',
        ],

        'kapanewon' => [
            'Tanjungsari',
            'Gedangsari',
            'Wonosari',
            'Playen',
            'Pathuk',
            'Pandak',
            'Nanggulan',
            'Danurejan',
            'Gedongtengen',
            'Gondokusuman',
            'Gondomanan',
            'Jetis',
            'Kotagede',
            'Kraton',
            'Mantrijeron',
            'Mergangsan',
            'Ngampilan',
            'Pakualaman',
            'Tegalrejo',
            'Umbulharjo',
            'Wirobrajan',
            'Prambanan',
        ],
        'kabupaten' => [
            'Bantul',
            'Gunungkidul',
            'Kulonprogo',
            'Sleman',
            'Yogyakarta',
        ],

    ],


];
